//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Applications))]
    [KnownType(typeof(aspnet_Membership))]
    [KnownType(typeof(aspnet_PersonalizationPerUser))]
    [KnownType(typeof(aspnet_Profile))]
    [KnownType(typeof(Bank))]
    [KnownType(typeof(Department))]
    [KnownType(typeof(Hall))]
    [KnownType(typeof(Student))]
    [KnownType(typeof(aspnet_Roles))]
    public partial class aspnet_Users
    {
        public aspnet_Users()
        {
            this.aspnet_PersonalizationPerUser = new HashSet<aspnet_PersonalizationPerUser>();
            this.Banks = new HashSet<Bank>();
            this.Departments = new HashSet<Department>();
            this.Halls = new HashSet<Hall>();
            this.Students = new HashSet<Student>();
            this.aspnet_Roles = new HashSet<aspnet_Roles>();
        }
    
        [DataMember]
        public System.Guid ApplicationId { get; set; }
        [DataMember]
        public System.Guid UserId { get; set; }
        [DataMember]
        public string UserName { get; set; }
        [DataMember]
        public string LoweredUserName { get; set; }
        [DataMember]
        public string MobileAlias { get; set; }
        [DataMember]
        public bool IsAnonymous { get; set; }
        [DataMember]
        public System.DateTime LastActivityDate { get; set; }
    
        [DataMember]
        public virtual aspnet_Applications aspnet_Applications { get; set; }
        [DataMember]
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        [DataMember]
        public virtual ICollection<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        [DataMember]
        public virtual aspnet_Profile aspnet_Profile { get; set; }
        [DataMember]
        public virtual ICollection<Bank> Banks { get; set; }
        [DataMember]
        public virtual ICollection<Department> Departments { get; set; }
        [DataMember]
        public virtual ICollection<Hall> Halls { get; set; }
        [DataMember]
        public virtual ICollection<Student> Students { get; set; }
        [DataMember]
        public virtual ICollection<aspnet_Roles> aspnet_Roles { get; set; }
    }
    
}
