//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Users))]
    public partial class Bank
    {
        [DataMember]
        public System.Guid BankId { get; set; }
        [DataMember]
        public System.Guid UserId { get; set; }
        [DataMember]
        public string BankName { get; set; }
    
        [DataMember]
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
    
}
