//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Users))]
    [KnownType(typeof(Student))]
    public partial class Department
    {
        public Department()
        {
            this.Students = new HashSet<Student>();
        }
    
        [DataMember]
        public System.Guid DepartmentId { get; set; }
        [DataMember]
        public Nullable<System.Guid> UserId { get; set; }
        [DataMember]
        public string DepartmentName { get; set; }
    
        [DataMember]
        public virtual aspnet_Users aspnet_Users { get; set; }
        [DataMember]
        public virtual ICollection<Student> Students { get; set; }
    }
    
}
