//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Hall))]
    public partial class ExamFee
    {
        [DataMember]
        public System.Guid ExamFeeId { get; set; }
        [DataMember]
        [Display (Name = "Examination Fee")]
        public decimal ExamFee1 { get; set; }
        [DataMember]
        [Display(Name = "Centre Fee")]
        public decimal CentreFee { get; set; }
        [DataMember]
        [Display(Name = "Transcript Fee")]
        public decimal TranscriptFee { get; set; }
        [DataMember]
        [Display(Name = "Hall Name")]
        public System.Guid HallId { get; set; }
        [DataMember]
        [Display(Name = "Last Date")]
        public System.DateTime LastDate { get; set; }
        [DataMember]
        [Display(Name = "Total Amount")]
        public Nullable<decimal> Total { get; set; }
    
        [DataMember]
        public virtual Hall Hall { get; set; }
    }
    
}
