//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(AdmissionFee))]
    [KnownType(typeof(aspnet_Users))]
    [KnownType(typeof(ExamFee))]
    [KnownType(typeof(Student))]
    public partial class Hall
    {
        public Hall()
        {
            this.AdmissionFees = new HashSet<AdmissionFee>();
            this.ExamFees = new HashSet<ExamFee>();
            this.Students = new HashSet<Student>();
        }
    
        [DataMember]
        public System.Guid HallId { get; set; }
        [DataMember]
        public System.Guid UserId { get; set; }
        [DataMember]
        public string HallName { get; set; }
    
        [DataMember]
        public virtual ICollection<AdmissionFee> AdmissionFees { get; set; }
        [DataMember]
        public virtual aspnet_Users aspnet_Users { get; set; }
        [DataMember]
        public virtual ICollection<ExamFee> ExamFees { get; set; }
        [DataMember]
        public virtual ICollection<Student> Students { get; set; }
    }
    
}
