//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(aspnet_Users))]
    [KnownType(typeof(Department))]
    [KnownType(typeof(Hall))]
    [KnownType(typeof(StudentYearStatu))]
    [KnownType(typeof(Transaction))]
    public partial class Student
    {
        public Student()
        {
            this.StudentYearStatus = new HashSet<StudentYearStatu>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        [DataMember]
        public System.Guid StudentId { get; set; }
        [DataMember]
        [Display(Name = "Student Name")]
        public string Name { get; set; }
        [DataMember]
        [Display(Name = "Father Name")]
        public string FatherName { get; set; }
        [DataMember]
        [Display(Name = "Mother Name")]
        public string MotherName { get; set; }
        [DataMember]
        [Display(Name = "Current Address")]
        public string CurrentAddress { get; set; }
        [DataMember]
        [Display(Name = "Permanent Address")]
        public string PermanentAddress { get; set; }
        [DataMember]
        [Display(Name = "Contact Number")]
        public string ContactNumber { get; set; }
        [DataMember]
        [Display(Name = "Year of Passing SSC")]
        public Nullable<int> SSCYear { get; set; }
        [DataMember]
        [Display(Name = "Year of Passing HSC")]
        public Nullable<int> HSCYear { get; set; }
        [DataMember]
        [Display(Name = "GPA of SSC")]
        public Nullable<decimal> SSCGPA { get; set; }
        [DataMember]
        [Display(Name = "GPA of HSC")]
        public Nullable<decimal> HSCGPA { get; set; }
        [DataMember]
        [Display(Name = "Session")]
        public string Session { get; set; }
        [DataMember]
        [Display(Name = "Name of Department")]
        public System.Guid DepartmentId { get; set; }
        [DataMember]
        [Display(Name = "Name of Hall")]
        public System.Guid HallId { get; set; }
        [DataMember]
        [Display(Name = "User Name")]
        public System.Guid UserId { get; set; }
        [DataMember]
        [Display(Name = "Registration Number")]
        public string RegistrationNumber { get; set; }
    
        [DataMember]
        public virtual aspnet_Users aspnet_Users { get; set; }
        [DataMember]
        public virtual Department Department { get; set; }
        [DataMember]
        public virtual Hall Hall { get; set; }
        [DataMember]
        public virtual ICollection<StudentYearStatu> StudentYearStatus { get; set; }
        [DataMember]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
    
}
