//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace AdmissionFinal.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Student))]
    public partial class Transaction
    {
        [DataMember]
        public System.Guid TransactionId { get; set; }
        [DataMember]
        [Display(Name = "Student Name")]
        public System.Guid StudentId { get; set; }
        [DataMember]
        [Display(Name = "Received Amount")]
        public decimal? Amount { get; set; }
        [DataMember]
        [Display(Name = "Receive Date")]
        public System.DateTime Date { get; set; }
    
        [DataMember]
        public virtual Student Student { get; set; }
    }
    
}
